import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/core/auth/session";
import { prisma } from "@/core/database/prisma";
import { orgReportsService } from "@/modules/org/reports/reports.service";
import { ReportStatus } from "@/generated/prisma/enums";
import { logger } from "@/core/logger/pino";

/**
 * GET /api/org/reports/export?format=csv&status=&q=
 *
 * Streams a CSV of the org's reports matching the same filters as the
 * list endpoint.
 */
export async function GET(req: NextRequest) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json(
        { success: false, message: "Not authenticated" },
        { status: 401 }
      );
    }
    const membership = await prisma.organizationMember.findFirst({
      where: { userId: user.id, organization: { deletedAt: null } },
    });
    if (!membership) {
      return NextResponse.json(
        { success: false, message: "No organization for user" },
        { status: 404 }
      );
    }
    const { searchParams } = new URL(req.url);
    const result = await orgReportsService.getReports(membership.organizationId, {
      q: searchParams.get("q") ?? undefined,
      status: (searchParams.get("status") as keyof typeof ReportStatus) || undefined,
      limit: 1000,
      page: 1,
    });

    const escape = (v: unknown) => {
      if (v == null) return "";
      const s = String(v).replace(/"/g, '""');
      return /[",\n]/.test(s) ? `"${s}"` : s;
    };
    const header = [
      "Report ID",
      "Asset",
      "Status",
      "Version",
      "Generated At",
      "Generated By",
    ].join(",");
    const rows = result.rows.map((r) =>
      [
        r.id,
        r.assetName,
        r.status,
        r.reportVersion,
        r.generatedAt,
        r.generatedBy?.fullName,
      ]
        .map(escape)
        .join(",")
    );
    const csv = [header, ...rows].join("\n");
    return new NextResponse(csv, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="org-reports-${new Date()
          .toISOString()
          .slice(0, 10)}.csv"`,
      },
    });
  } catch (error: any) {
    logger.error({ err: error }, "Failed to export org reports");
    return NextResponse.json(
      { success: false, message: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}
