import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/core/database/prisma";
import { getCurrentUser } from "@/core/auth/session";
import { projectService } from "@/modules/marketplace/project/project.service";
import { SubscriptionType } from "@/generated/prisma/enums";
import { logger } from "@/core/logger/pino";

/**
 * GET /api/marketplace/projects/[id]/concept-note
 *
 * Returns the gated concept-note document for a project.
 * `id` may be a UUID or a slug (handled by `projectService.getProjectByIdOrSlug`).
 *
 * Auth: requires an active MARKETPLACE or BUNDLE subscription.
 *
 * Response (JSON):
 *   {
 *     success: true,
 *     data: {
 *       project: { id, slug, title, conceptNoteUrl, milestones, ... },
 *       // Optional structured content if the project has no PDF:
 *       sections?: [{ heading, content }],
 *     }
 *   }
 *
 * If the project has a `conceptNoteUrl` set (PDF), the response includes
 * the URL and a pre-signed download URL is *not* generated by default —
 * the client fetches the file directly. If the file lives in S3 and
 * requires a signed URL, replace the `conceptNoteUrl` with a server-side
 * `getSignedUrl` call.
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json(
        { success: false, message: "Not authenticated" },
        { status: 401 }
      );
    }

    // Fetch project by id or slug
    let project;
    try {
      project = await projectService.getProjectByIdOrSlug(id);
    } catch {
      return NextResponse.json(
        { success: false, message: "Project not found" },
        { status: 404 }
      );
    }

    // Subscription gate — MARKETPLACE or BUNDLE only
    const activeSub = await prisma.subscription.findFirst({
      where: {
        userId: user.id,
        status: "ACTIVE",
        plan: {
          type: {
            in: [SubscriptionType.MARKETPLACE, SubscriptionType.BUNDLE],
          },
        },
      },
      include: { plan: true },
    });
    if (!activeSub) {
      return NextResponse.json(
        {
          success: false,
          message:
            "An active MARKETPLACE or BUNDLE subscription is required to access concept notes.",
        },
        { status: 403 }
      );
    }

    return NextResponse.json(
      {
        success: true,
        data: {
          project: {
            id: project.id,
            slug: project.slug,
            title: project.title,
            conceptNoteUrl: project.conceptNoteUrl,
            milestones: project.milestones,
            recommendations: project.recommendations,
            forecast: project.forecast,
          },
        },
      },
      { status: 200 }
    );
  } catch (error: any) {
    logger.error({ err: error }, "Failed to fetch concept note");
    return NextResponse.json(
      { success: false, message: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}
