/**
 * Pure formatter for the invoice text downloaded from
 * `GET /api/billing/invoices/{id}/download?format=text`.
 *
 * Kept as a pure function so it can be unit-tested without spinning up
 * NextRequest / Prisma.
 */

export interface InvoiceInput {
  paymentId: string;
  paidAt: Date | string | null;
  createdAt: Date | string;
  amount: unknown; // Prisma Decimal | number | string | null
  currency: string | null;
  paymentProvider?: string | null;
  providerPaymentId?: string | null;
  subscription?: { plan?: { name?: string | null; type?: string | null } } | null;
  user?: {
    id?: string;
    fullName?: string | null;
    email?: string | null;
  } | null;
}

const BAR = "=".repeat(74);

export function formatInvoiceNumber(paymentId: string): string {
  // Friendly short id — matches what the JSON envelope returns.
  return `INV-${paymentId.slice(0, 8).toUpperCase()}`;
}

export function formatDateUtc(d: Date | string | null | undefined): string {
  if (!d) return "—";
  const date = typeof d === "string" ? new Date(d) : d;
  if (Number.isNaN(date.getTime())) return "—";
  return date.toUTCString();
}

export function formatAmount(amount: unknown): number {
  if (amount == null) return 0;
  if (typeof amount === "number") return amount;
  // Prisma.Decimal exposes toString() — parse defensively.
  const n = Number(amount.toString());
  return Number.isFinite(n) ? n : 0;
}

/**
 * Renders the plain-text invoice body. Always returns a string with a
 * trailing newline so the response can stream it directly.
 */
export function formatInvoiceText(payment: InvoiceInput): string {
  const number = formatInvoiceNumber(payment.paymentId);
  const issuedAt = payment.paidAt ?? payment.createdAt;
  const amount = formatAmount(payment.amount);
  const currency = payment.currency ?? "INR";
  const planName = payment.subscription?.plan?.name ?? "Subscription";
  const planType = payment.subscription?.plan?.type ?? null;
  const providerName = payment.paymentProvider ?? "unknown";
  const providerId = payment.providerPaymentId ?? "—";
  const fullName = payment.user?.fullName ?? "—";
  const email = payment.user?.email ?? "—";

  const lines = [
    BAR,
    "  PRANA EARTH — INVOICE",
    BAR,
    "",
    `Invoice #:      ${number}`,
    `Issued:         ${formatDateUtc(issuedAt)}`,
    `Status:         PAID`,
    ``,
    `Bill to:`,
    `  ${fullName}`,
    `  ${email}`,
    ``,
    `Item:`,
    `  ${planName}${planType ? ` (${planType})` : ""}`,
    ``,
    `Amount:         ${currency} ${amount.toFixed(2)}`,
    `Provider:       ${providerName}`,
    `Provider ID:    ${providerId}`,
    ``,
    `Internal ref:   ${payment.paymentId}`,
    ``,
    BAR,
    `  Generated by Prana Earth API`,
    BAR,
  ];
  return lines.join("\n") + "\n";
}

/**
 * `Content-Disposition: attachment` header value for the given
 * payment id, computed once and shared by the route + tests.
 */
export function buildAttachmentHeader(paymentId: string): string {
  return `attachment; filename="${formatInvoiceNumber(paymentId)}.txt"`;
}
